[package]
name = "ann"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
rand = "0.8"
=======
rand = "0.8"
rayon = "1.7.0"
>>>>>>> c58194c1d23e36c03236a0acf64cd92563c93258
